# Configuration with perfect link, a generic qdevice, but some noise on the generic device
qdevice_cfg: &qdevice_cfg
  num_qubits: 10

  # coherence times in ns(same for each qubit) min requirement
  T1: 10_000_000_000_000_000
  T2: 1_000_000_000_000_000

  # gate execution times in ns
  init_time: 10_000
  single_qubit_gate_time: 1_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000

  # noise model
  single_qubit_gate_depolar_prob: 0.0
  two_qubit_gate_depolar_prob: 0.0

stacks:
  - name: client
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: server
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

links:
  - stack1: client
    stack2: server
    typ: perfect
    cfg:
      dummy: null