# Fidelity between the EPR pair qubits
fidelity: 0.9461
# Time in nanoseconds for an attempt to generated entanglement
#t_cycle: 10.
distance: 1
# Chance for each attempt at entanglement to succeed
prob_success: 1
speed_of_light: 214000