# Trapped ion configuration based on Appendix A.6 of https://arxiv.org/abs/2207.10579

qdevice_client_cfg: &client_cfg
  num_qubits: 10

  # coherence times (same for each qubit), all in ns
  T1: 1e99  # Disabled amplitude dampening
  T2: 1e90  # 85 ms

  # gate execution times, all in ns
  init_time: 10_000
  single_qubit_gate_time: 1_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000

  # noise model, all probabilities
  single_qubit_gate_depolar_prob: 0
  two_qubit_gate_depolar_prob: 0

qdevice_server_cfg: &server_cfg
  num_qubits: 10

  # coherence times (same for each qubit), all in ns
  T1: 12.3285e97 # Disabled amplitude dampening
  T2: 12.3285e8  # 85 ms

  # gate execution times, all in ns
  init_time: 10_000
  single_qubit_gate_time: 1_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000

  # noise model, all probabilities
  single_qubit_gate_depolar_prob: 0.0008
  two_qubit_gate_depolar_prob: 0.00314

stacks:
  - name: client
    qdevice_typ: generic
    qdevice_cfg:
      <<: *server_cfg
  - name: server
    qdevice_typ: generic
    qdevice_cfg:
      <<: *server_cfg


link_cfg: &link_cfg
    length: 10  # km
    p_loss_init: 0.889 #  probability  1 - 0.111
    p_loss_length: 0.25  # dB/km
    speed_of_light: 214_000  # km/s
    dark_count_probability: 1.4e-5  #  probability
    detector_efficiency: 0.98  #  probability
    visibility: 0.89
    num_resolving: False

links:
  - stack1: client
    stack2: server
    typ: heralded
    cfg:
      <<: *link_cfg

clinks:
  - stack1: client
    stack2: server
    typ: default
    cfg:
      delay: 20